services:
  api:
    image: template-api:local
    container_name: api
    env_file:
      - apps/api/.env.docker.local
    ports:
      - '3000:3000'
    profiles:
      # only run with `docker-compose --profile api-local-container up`
      - api-local-container
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
  postgres-test:
    image: postgres:18
    container_name: postgres-test
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=postgres-test
      - POSTGRES_DB=nestjs
    ports:
      - '5433:5432'
    volumes:
      - postgres-test_data:/var/lib/postgresql

volumes:
  postgres_data:
  postgres-test_data:
